sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oGoTX15oMFv0OcDDV1v3V+HUVg/4sPTYxLiM6OJoPts8Ez2PRFeojHS+wwGXfSQMIWtTqoozzd4dwj8U+CSOZNVTl+IDJvuK0jCO99RfTg7K6H+wDm+GxsJv34/6+bjAdjdV7+tLBbmClMBVUEeOIe0Ho+OXnbiBGf52+QPFiAe34jZVBK2wq3xUnB/Cc4ja/wJDEuBiy1YMeU10VofxoJU/p+N529rhRjD9n7DLLNphwss45r88qa2064IdZtr3a48/6qvGyaA/k+mdnES/eCrYRCRcT0LX27+2AApMEsQ2QHY/TZlBhdrUCYzvwLhlt+Ku1tlcv+4s8iVqJqjVzOXPdrYN22OKrFcfzahwoYCLJeN/5dBjIk4z5rRbomNi/qOKH9l1Lg2xu5HBEvk1IioUkmuYbpEolju/C2CwB+bdLltgXJ9pH7+nEsrdhyBeUgZwxHsePWrgBRlYxJ4Hx/ffqr+FUq82c6KHoNYFFHu3Il44jIHUdAROhLEhWTjOxCkKQrpaCi2RFF7jVgKij30f3tDPfiJ7dwdURb5awULHk4xDv3CluGHmzwg8HdMx3u9L5iqxtE0EBg0rMi1ZgSMi2Ll5G8XQJp/ffpxlPK5IKLL7BwwrCykuYc/+F15kJj4D/Kkpxf/rjY+cQIBd3VeAuPsc9OedRj5GdS+UDMY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Celtic-Literature_5159
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy